using UnityEngine;
using UnityEngine.Rendering;

namespace VEVE.Graphics
{
    /// <summary>
    /// Combines an authored base normal map with a procedural micro-detail normal generated by
    /// <see cref="ProceduralSurfaceTextureFactory"/>, using Unity's built-in Standard shader detail slots.
    /// <para>
    /// Standard shader property contract (verified against the shipped Standard.shader source):
    /// <c>_BumpMap</c> + <c>_BumpScale</c> (base normal, keyword <c>_NORMALMAP</c>) and
    /// <c>_DetailNormalMap</c> + <c>_DetailNormalMapScale</c> for the secondary normal layer. Note the scale
    /// property is <c>_DetailNormalMapScale</c>, NOT <c>_DetailNormalScale</c> (an HDRP-style name that does
    /// not exist on the built-in Standard shader). Detail maps are sampled unconditionally; the optional
    /// <c>_DETAIL_MULX2</c> shader_feature switches XY combine from Whiteout (off, correct for micro detail:
    /// multiplies detail XY and keeps base Z) to Multiply (on) and is intentionally never toggled here so the
    /// component composes with the material author's choice.
    /// </para>
    /// <para>
    /// Texture overrides go through a <see cref="MaterialPropertyBlock"/>, so shared materials are never
    /// mutated and batching is preserved. If <see cref="ProceduralSurfaceKind.IsNonPorous"/> is true (glass)
    /// or the factory bundle is not ready yet, the component silently does nothing and re-applies via the
    /// factory's <c>BundleReady</c> event once textures exist. Runtime-only: no editor APIs.
    /// </para>
    /// </summary>
    [DisallowMultipleComponent]
    [RequireComponent(typeof(Renderer))]
    public sealed class MicroDetailNormalBlender : MonoBehaviour
    {
        [Tooltip("Surface category whose micro-detail normal is blended onto this renderer.")]
        [SerializeField] private ProceduralSurfaceKind surfaceKind = ProceduralSurfaceKind.Concrete;

        [Tooltip("Blend weight for the procedural detail layer. 0 disables the detail map; 1 is full Whiteout strength.")]
        [Range(0f, 1f)]
        [SerializeField] private float detailScale = 0.45f;

        [Tooltip("Keeps the renderer's own authored _BumpMap in place instead of substituting the procedural normal as base map.")]
        [SerializeField] private bool preserveAuthoredBaseNormal = true;

        private static readonly int BumpMapId = Shader.PropertyToID("_BumpMap");
        private static readonly int BumpScaleId = Shader.PropertyToID("_BumpScale");
        private static readonly int DetailNormalMapId = Shader.PropertyToID("_DetailNormalMap");
        private static readonly int DetailNormalScaleId = Shader.PropertyToID("_DetailNormalMapScale");
        private const string NormalMapKeyword = "_NORMALMAP";

        private Renderer targetRenderer;
        private MaterialPropertyBlock propertyBlock;
        private bool applied;

        /// <summary>Surface category driven by this blender.</summary>
        public ProceduralSurfaceKind SurfaceKind
        {
            get => surfaceKind;
            set
            {
                if (surfaceKind != value)
                {
                    surfaceKind = value;
                    applied = false;
                    ApplyDetail();
                }
            }
        }

        /// <summary>Detail blend weight; drives <c>_DetailNormalScale</c>.</summary>
        public float DetailScale
        {
            get => detailScale;
            set
            {
                detailScale = Mathf.Clamp01(value);
                applied = false;
                ApplyDetail();
            }
        }

        private void Awake()
        {
            targetRenderer = GetComponent<Renderer>();
            propertyBlock = new MaterialPropertyBlock();
            TryApplyFromFactory();
        }

        private void OnEnable()
        {
            ProceduralSurfaceTextureFactory factory = ProceduralSurfaceTextureFactory.Instance;
            if (factory != null)
            {
                factory.BundleReady += OnBundleReady;
            }

            applied = false;
            TryApplyFromFactory();
        }

        private void OnDisable()
        {
            ProceduralSurfaceTextureFactory factory = ProceduralSurfaceTextureFactory.Instance;
            if (factory != null)
            {
                factory.BundleReady -= OnBundleReady;
            }
        }

        private void OnBundleReady(CachedTextureBundle bundle)
        {
            if (this == null || bundle.Kind != surfaceKind)
            {
                return;
            }

            applied = false;
            TryApplyFromFactory();
        }

        private void TryApplyFromFactory()
        {
            ProceduralSurfaceTextureFactory factory = ProceduralSurfaceTextureFactory.Instance;
            if (factory == null)
            {
                return;
            }

            CachedTextureBundle bundle;
            if (factory.TryGetBundle(surfaceKind, out bundle))
            {
                ApplyDetail(bundle);
            }
        }

        /// <summary>
        /// Re-resolves the factory bundle and re-pushes the property block (e.g. after a shader or material swap).
        /// </summary>
        public void Refresh()
        {
            applied = false;
            TryApplyFromFactory();
        }

        /// <summary>
        /// Pushes the procedural micro normal into <c>_DetailNormalMap</c> / <c>_DetailNormalScale</c> on this
        /// renderer via MaterialPropertyBlock, without touching the shared material or the authored <c>_BumpMap</c>.
        /// </summary>
        /// <param name="bundle">Finished bundle from the procedural factory (must contain a Normal map).</param>
        public void ApplyDetail(CachedTextureBundle bundle)
        {
            if (targetRenderer == null || bundle == null || !bundle.IsReady)
            {
                return;
            }

            Renderer renderer = targetRenderer;
            if (propertyBlock == null)
            {
                propertyBlock = new MaterialPropertyBlock();
            }

            renderer.GetPropertyBlock(propertyBlock);
            Material material = renderer.sharedMaterial;

            if (material == null || !material.HasProperty(DetailNormalMapId))
            {
                return;
            }

            if (surfaceKind.IsNonPorous() || detailScale <= 0f)
            {
                propertyBlock.SetTexture(DetailNormalMapId, null);
                propertyBlock.SetFloat(DetailNormalScaleId, 0f);
                renderer.SetPropertyBlock(propertyBlock);
                applied = true;
                return;
            }

            propertyBlock.SetTexture(DetailNormalMapId, bundle.Normal);
            propertyBlock.SetFloat(DetailNormalScaleId, detailScale);
            renderer.SetPropertyBlock(propertyBlock);

            if (!preserveAuthoredBaseNormal && material.HasProperty(BumpMapId) && material.GetTexture(BumpMapId) == null)
            {
                material.EnableKeyword(NormalMapKeyword);

                propertyBlock.SetTexture(BumpMapId, bundle.Normal);
                propertyBlock.SetFloat(BumpScaleId, 1f);
                renderer.SetPropertyBlock(propertyBlock);
            }

            applied = true;
        }

        /// <summary>
        /// Convenience overload used by <see cref="TryApplyFromFactory"/> fallback path.
        /// </summary>
        public void ApplyDetail()
        {
            if (!applied)
            {
                TryApplyFromFactory();
            }
        }
    }
}
